# Generated by Django 6.0.5 on 2026-05-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROJECT_LEAD', 'project lead'), ('WRITER', 'writer'), ('REVIEWER', 'REVIEWRE'), ('client_viewer', 'CLIENT_VIEWER'), ('DESIGNER', 'designer')], max_length=50),
        ),
    ]
