# Generated by Django 6.0.5 on 2026-05-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_deadline_task_priority_alter_projectmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('project lead', 'PROJECT_LEAD'), ('WRITER', 'writer'), ('REVIEWER', 'REVIEWRE'), ('client_viewer', 'CLIENT_VIEWER'), ('DESIGNER', 'designer')], max_length=50),
        ),
    ]
