# Generated by Django 6.0.5 on 2026-05-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('PROJECT_LEAD', 'project lead'), ('writer', 'WRITER'), ('REVIEWER', 'REVIEWRE'), ('CLIENT_VIEWER', 'client_viewer'), ('DESIGNER', 'designer')], max_length=50),
        ),
    ]
