# Generated by Django 6.0.5 on 2026-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_user_notification_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Comment', 'comment'), ('task', 'Task'), ('Stage', 'stage_moved'), ('deadline', 'Deadline')], max_length=50),
        ),
    ]
