# Generated by Django 6.0.5 on 2026-05-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudioMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('PROJECT_LEAD', 'project lead'), ('WRITER', 'writer'), ('REVIEWER', 'REVIEWRE'), ('client_viewer', 'CLIENT_VIEWER'), ('DESIGNER', 'designer')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
