# Generated by Django 6.0.5 on 2026-05-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiomembership',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('project lead', 'PROJECT_LEAD'), ('writer', 'WRITER'), ('REVIEWRE', 'REVIEWER'), ('client_viewer', 'CLIENT_VIEWER'), ('DESIGNER', 'designer')], max_length=50),
        ),
    ]
