# Generated by Django 6.0.5 on 2026-05-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_studiomembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiomembership',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('project lead', 'PROJECT_LEAD'), ('writer', 'WRITER'), ('REVIEWER', 'REVIEWRE'), ('client_viewer', 'CLIENT_VIEWER'), ('designer', 'DESIGNER')], max_length=50),
        ),
    ]
