# Generated by Django 6.0.5 on 2026-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_alter_studiomembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiomembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROJECT_LEAD', 'project lead'), ('writer', 'WRITER'), ('REVIEWRE', 'REVIEWER'), ('CLIENT_VIEWER', 'client_viewer'), ('DESIGNER', 'designer')], max_length=50),
        ),
    ]
